openapi: 3.0.3
info:
  title: Alignment API
  version: 1.0.0
  description: Django alignment PAI
paths:
  /alignment/:
    get:
      operationId: alignment_list
      tags:
      - alignment
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Alignment'
          description: ''
    post:
      operationId: alignment_create
      tags:
      - alignment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alignment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Alignment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Alignment'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alignment'
          description: ''
  /alignment/{id}/:
    get:
      operationId: alignment_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - alignment
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alignment'
          description: ''
    put:
      operationId: alignment_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - alignment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Alignment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Alignment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Alignment'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alignment'
          description: ''
    patch:
      operationId: alignment_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - alignment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedAlignment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedAlignment'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedAlignment'
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alignment'
          description: ''
    delete:
      operationId: alignment_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - alignment
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /alignment/search/:
    get:
      operationId: alignment_search_retrieve
      parameters:
      - in: query
        name: genomes
        schema:
          type: array
          minItems: 1
          items:
            type: string
        description: Search for DNA sequence in a set of genome accession ids
      - in: query
        name: sequence
        schema:
          type: string
        description: DNA Sequence to search for
        required: true
      tags:
      - alignment
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alignment'
          description: Created new alignment search request
        '400':
          description: Bad request (something invalid)
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/token/:
    post:
      operationId: api_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: api_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
components:
  schemas:
    Alignment:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        search_sequence:
          type: string
          description: DNA sequence that you want to align
          maxLength: 50
        search_genomes:
          type: array
          items:
            $ref: '#/components/schemas/Genome'
          readOnly: true
        status:
          $ref: '#/components/schemas/StatusEnum'
        matched_genes:
          type: array
          items:
            $ref: '#/components/schemas/Gene'
          readOnly: true
        created:
          type: string
          format: date-time
          readOnly: true
        updated:
          type: string
          format: date-time
          readOnly: true
      required:
      - created
      - id
      - matched_genes
      - search_genomes
      - search_sequence
      - updated
    Gene:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        genome:
          allOf:
          - $ref: '#/components/schemas/Genome'
          readOnly: true
        sequence:
          type: string
          description: e.g. AACGGAATACCAGAGAG
        name:
          type: string
          description: e.g. a001L
        protein:
          type: string
          description: e.g. hypothetical protein
        db_xref:
          type: string
          description: e.g. GeneID:918202
        protein_id:
          type: string
          description: NP_048349.1'
      required:
      - db_xref
      - genome
      - id
      - name
      - protein
      - protein_id
      - sequence
    Genome:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        accession:
          type: string
          description: e.g. NC_000852
          maxLength: 50
      required:
      - accession
      - id
    PatchedAlignment:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        search_sequence:
          type: string
          description: DNA sequence that you want to align
          maxLength: 50
        search_genomes:
          type: array
          items:
            $ref: '#/components/schemas/Genome'
          readOnly: true
        status:
          $ref: '#/components/schemas/StatusEnum'
        matched_genes:
          type: array
          items:
            $ref: '#/components/schemas/Gene'
          readOnly: true
        created:
          type: string
          format: date-time
          readOnly: true
        updated:
          type: string
          format: date-time
          readOnly: true
    StatusEnum:
      enum:
      - created
      - running
      - success
      - failure
      type: string
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
