# Generated by Django 4.1.1 on 2022-09-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failure", "Failure"),
                ],
                default="created",
                max_length=15,
            ),
        ),
    ]
