# Generated by Django 4.1.1 on 2022-09-12 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alignment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accession",
                    models.CharField(help_text="e.g. NC_000852", max_length=50),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="alignment",
            name="search_sequence",
            field=models.CharField(
                help_text="DNA sequence that you want to align", max_length=50
            ),
        ),
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.TextField(help_text="e.g. AACGGAATACCAGAGAG")),
                ("name", models.TextField(help_text="e.g. a001L")),
                ("protein", models.TextField(help_text="e.g. hypothetical protein")),
                ("db_xref", models.TextField(help_text="e.g. GeneID:918202")),
                ("protein_id", models.TextField(help_text="NP_048349.1'")),
                (
                    "genome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.genome"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="alignment",
            name="matched_genes",
            field=models.ManyToManyField(to="api.gene"),
        ),
        migrations.AddField(
            model_name="alignment",
            name="search_genomes",
            field=models.ManyToManyField(to="api.genome"),
        ),
    ]
